Feature/releases support
wirenboard/wb-mcu-fw-updater pull request #16
Opened 2022-01-12 14:18 UTC by vdromanov

В упдатер приехали релизы. Поведение (копипаст из дев-чатика):
1) релизов нет (старый вб; нет /usr/lib/wb-release):
    - update-all не работает и предлагает или обновить контроллер, или обновить устройство руками (update-fw)
    - update-fw - старое поведение
    - recover - старое поведение
    - recover-all - старое поведение

2) релизы есть (новый вб):
   - update-fw смотрит в релизы и берет версию оттуда. Если для текущих suite/repo_prefix/fw_sig прошивки нет - спрашивает, скачать ли latest
   - update-fw --version берет версию, которую указали - полностью старое поведение
   - update-all смотрит только в релизы. Если прошивки для устройства нет - пропускает его обновление и ругается
   - recover смотрит в релизы. Если не нашел прошивку - спрашивает, скачать ли из stable/latest
   - recover-all смотрит только в релизы
   
Гонял упдатер во всех режимах для:

- вб без /usr/lib/wb-release
- вб с /usr/lib/wb-release (но для устройств не прописаны прошивки)
- прошивки указаны в релизе

2022-01-12 14:21 UTC, vdromanov commented
я тут подумал: мб в update-all разрешим даунгрейд прошивок? (сейчас не сделано)
а то сейчас упдатер может сказать: "Remote fw version (4.16.5) is less than local on WB-M1W2 (port: /dev/ttyRS485-2; slaveid: 3) (4.16.19)"

впишется в концепцию переходов между stable/testing релизами

2022-01-12 14:24 UTC, webconn commented
> я тут подумал: мб в update-all разрешим даунгрейд прошивок? (сейчас не сделано) а то сейчас упдатер может сказать: "Remote fw version (4.16.5) is less than local on WB-M1W2 (port: /dev/ttyRS485-2; slaveid: 3) (4.16.19)"

Определённо стоит. Для безопасности можно включать её флагом, а флаг использовать по умолчанию в утилите wb-release.

Кстати, напомни, мы по умолчанию спрашиваем у пользователя, устраивает ли его то, что случится при обновлении (как это делает `apt upgrade`?)

2022-01-12 14:26 UTC, vdromanov commented
> > я тут подумал: мб в update-all разрешим даунгрейд прошивок? (сейчас не сделано) а то сейчас упдатер может сказать: "Remote fw version (4.16.5) is less than local on WB-M1W2 (port: /dev/ttyRS485-2; slaveid: 3) (4.16.19)"
> 
> Определённо стоит. Для безопасности можно включать её флагом, а флаг использовать по умолчанию в утилите wb-release.
> 
> Кстати, напомни, мы по умолчанию спрашиваем у пользователя, устраивает ли его то, что случится при обновлении (как это делает `apt upgrade`?)

Для прошивок - нет (и вопрос - нужно ли? т.к. операция вполне обратимая). Для бутлоадера - да (и ругаемся о потере гарантии)

2022-01-12 14:33 UTC, webconn commented
У нас при обновлении прошивок сейчас ведь могут потеряться какие-нибудь настройки из flashfs (например, записанные команды из mir). Мне кажется, это не позволяет нам принудительно обновлять устройства при смене релиза.

Впрочем, даже с интерактивным режимом нас это не спасёт, там слишком большая простыня текста получается, кто-то её 100% не прочтёт и расстроится из-за результата. А внутри компании у нас вообще временами wb-release запускают в неинтерактивном режиме.

Я так понимаю, что пока что нам стоит ограничиться тем, что как-то отдельно предлагать пользователю обновить прошивки при смене релиза, и разбираться с ним там уже вручную. В этом случае мне поведение интерактивного apt кажется правильным и уместным, к нему в debian-среде наверняка все привыкли. Ну или как минимум предупреждать, если обновление прошивки повлечёт за собой потерю конфигурации, и переспрашивать подтверждение

2022-01-14 15:21 UTC, webconn requested changes
Тут есть большой вопрос про логику (да, до ревью не вникал в этот вопрос так серьёзно).

Если прошивка не представлена в текущем релизе, надо так и сказать, что прошивки нету и вам надо обновиться, если хотите работать с устройством. Пытаться устанавливать `latest` не особо осмысленно, потому что устройство может с успехом не быть представлено в `wb-mqtt-serial`, а мы как раз хотим консистентности.

2022-01-14 15:21 UTC, webconn commented on wb_mcu_fw_updater/update_monitor.py
>          raise RuntimeError('FW file was not downloaded!')
А вот тут вроде ок с исключениями ;)
И то тут можно было бы получить больше интересной инфы, если бы исключение лезло изнутри функции

2022-01-14 15:21 UTC, webconn commented on wb_mcu_fw_updater/update_monitor.py
> +            specified_fw_version = 'latest'
Нене, плохо, надо в этом случае говорить, что железка не поддерживается и юзайте на свой страх и риск

2022-01-14 15:21 UTC, webconn commented on wb_mcu_fw_updater/update_monitor.py
> +        die('"update-all" mode works only for releases!\nPossible solutions:\n\trun "apt update; apt upgrade" and migrate to releases system\n\tmanually update each device "wb-mcu-fw-updater update-f
Тут эти советы не помогут, пакет-то будет установлен только вместе с релизами. Для уверенности можно даже поставить зависимость от пакета `wb-release-info` в `debian/control`, чтобы ручками у людей тоже не получилось установить.

Короче, лучше тут вывести сообщение о том, что у вас что-то сильно сломалось и лучше обратиться в поддержку.

2022-01-14 15:21 UTC, webconn commented on wb_mcu_fw_updater/update_monitor.py
> +            logging.info("Update skipped: %s (no releases)" % str(device_info))
Это тут что означает? что прошивка не включена в выбранный релиз?

Кстати, если это так, в будущем тут можно было бы писать, что "устройство в вашем релизе не поддерживается, но можете попробовать в более новом" (более новый - не обязательно testing; если есть в последнем stable, это лучше).

2022-01-14 15:25 UTC, webconn commented
Давай тут тоже расставим точки.

> В упдатер приехали релизы. Поведение (копипаст из дев-чатика):
> 
>     1. релизов нет (старый вб; нет /usr/lib/wb-release):
Этот сценарий в принципе невозможен, на дорелизный wb этот пакет установить нельзя.

>        
>        * update-all не работает и предлагает или обновить контроллер, или обновить устройство руками (update-fw)
>        * update-fw - старое поведение
>        * recover - старое поведение
>        * recover-all - старое поведение
> 
>     2. релизы есть (новый вб):
>        
>        * update-fw смотрит в релизы и берет версию оттуда. Если для текущих suite/repo_prefix/fw_sig прошивки нет - спрашивает, скачать ли latest
Правильно - если для текущего состояния системы прошивки нет - сказать, что не поддерживается, и по возможности подсказать, куда можно обновиться для поддержки (до stable или testing) и дать ссылку на инструкцию.

Как вариант, можно разрешить установить не релизную версию, если пользователь явно указал нужную ему версию аргументом, и то выругаться, что так вообще-то не стоит делать.

>        * update-fw --version берет версию, которую указали - полностью старое поведение
Ок.

>        * update-all смотрит только в релизы. Если прошивки для устройства нет - пропускает его обновление и ругается
>        * recover смотрит в релизы. Если не нашел прошивку - спрашивает, скачать ли из stable/latest
см. пункт про `update-fw`

>        * recover-all смотрит только в релизы
Ок.

> 
> 
> Гонял упдатер во всех режимах для:
> 
>     * вб без /usr/lib/wb-release
> 
>     * вб с /usr/lib/wb-release (но для устройств не прописаны прошивки)
> 
>     * прошивки указаны в релизе
> 
> 
> релизный файлик использовал [этот](http://fw-releases.wirenboard.com/fw/by-signature/release-versions.git~feature~34944~firmware~releases~2104.yaml)

2022-01-17 11:52 UTC, vdromanov commented on wb_mcu_fw_updater/__init__.py
> +    'FW_SIGNATURES_FILE_URL' : 'http://fw-releases.wirenboard.com/fw/by-signature/fw_signatures.txt',
готово

2022-01-17 11:52 UTC, vdromanov commented on wb_mcu_fw_updater/fw_downloader.py
> +def get_releases_info(remote_fname=CONFIG['FW_RELEASES_FILE_URL']):
готово

2022-01-17 11:52 UTC, vdromanov commented on wb_mcu_fw_updater/fw_downloader.py
> +        fh = open(file_path, 'wb+')
готово

2022-01-17 11:52 UTC, vdromanov commented on wb_mcu_fw_updater/fw_downloader.py
> +            logging.error('Could not download fw: signature %s, version %s, branch %s' % (
готово

2022-01-17 11:52 UTC, vdromanov commented on wb_mcu_fw_updater/fw_downloader.py
> +                os.mkdir(file_saving_dir)
готово
удобная штука, спасибо!

2022-01-17 11:52 UTC, vdromanov commented on wb_mcu_fw_updater/releases.py
> +        logging.warning("Releases file %s not found" % fname)
ну тут в целом у меня подход неправильный: зачем-то поддерживал сценарии, когда wb-releases нет, хотя это решается силами апта

в общем, теперь:
точка входа => прожевал wb-releases - хорошо; не прожевал => у вас всё сломалось, зовите поддержку

2022-01-17 11:52 UTC, vdromanov commented on wb_mcu_fw_updater/releases.py
> +    if os.path.exists(fname):
готово

2022-01-17 11:52 UTC, vdromanov commented on wb_mcu_fw_updater/releases.py
> +def parse_releases(fname=CONFIG['RELEASES_FNAME']):
написал todo

2022-01-17 11:52 UTC, vdromanov commented on wb_mcu_fw_updater/update_monitor.py
> +from yaml import safe_load
готово

2022-01-17 11:52 UTC, vdromanov commented on wb_mcu_fw_updater/update_monitor.py
> +    elif ask_user('No releases for "%s" found.\nPerform downloading fw from latest master (could possibly have bugs)?' % fw_signature):
готово

2022-01-17 11:53 UTC, vdromanov commented on wb_mcu_fw_updater/update_monitor.py
> +            specified_fw_version = 'latest'
готово

даже спрашиваем подтверждения

2022-01-17 11:53 UTC, vdromanov commented on wb_mcu_fw_updater/update_monitor.py
> +        die('"update-all" mode works only for releases!\nPossible solutions:\n\trun "apt update; apt upgrade" and migrate to releases system\n\tmanually update each device "wb-mcu-fw-updater update-f
готово

только помираем теперь уже у точки входа (см коммент выше)

2022-01-17 11:53 UTC, vdromanov commented on wb_mcu_fw_updater/update_monitor.py
> +            logging.info("Update skipped: %s (no releases)" % str(device_info))
да, всё верно

немного поправил сообщение и написал todo

2022-01-18 09:18 UTC, vdromanov commented
всё, что обсуждали - сделал
завёз даунгрейд прошивок (по ключу)
гонял - мне всё нравится

есть один принципиальный момент: хочу оставить возможность скачивания latest/master для неподдерживаемых устройств в режиме recover (сейчас - такое поведение)
аргументы:

1. руками чинить зависшее в бутлоадере устройство сильно сложнее, чем неконсистентный софт (под капотом одних и тех же устройств могут быть много разных fw-sig; тут и начнутся приключения)
2. если у человека неподдерживаемое устройство застряло в бутлоадере - он явно знает, что делает:)

2022-01-18 09:29 UTC, evgeny-boger commented
так, а оно умеет в бутлодере вычитывать сигнатуру?

2022-01-18 09:31 UTC, webconn commented
> есть один принципиальный момент: хочу оставить возможность установки latest/master для неподдерживаемых устройств в режиме recover

На такие случаи хорошо бы флагами выпутываться, чтобы было из запуска команды понятно, что произойдёт что-то необычное

2022-01-18 09:39 UTC, vdromanov commented
> так, а оно умеет в бутлодере вычитывать сигнатуру?

да
но в полях-то бутлоадер свежий не у всех

2022-01-18 10:06 UTC, webconn commented on wb_mcu_fw_updater/update_monitor.py
> +        logging.warning('Device "%s" is not supported in release "%s %s"' % (fw_signature, str(release_info.get('SUITE')), str(release_info.get('RELEASE_NAME'))))
У нас в баннере при входе используется формат `RELEASE_NAME (as SUITE)`, лучше тут сделать так же

2022-01-18 12:09 UTC, vdromanov commented on wb_mcu_fw_updater/fw_downloader.py
> +            raise e
готово

2022-01-18 12:09 UTC, vdromanov commented on wb_mcu_fw_updater/releases.py
> +from posixpath import join as urljoin
в py2 по-другому
есть 3 варианта:

- взять ``urlparse.urlparse``для py2; добавить проверку py2/3
- выкинуть py2; долго
- оставить, как есть (+ комментий)

я за последний вариант (сделан - он)

по поводу убрать py2 - всецело поддерживаю, но тут, как минимум, придется перевести весть test-suite. Давай запланируем в рамках приведение в порядок python-инфраструктуры?

2022-01-18 12:09 UTC, vdromanov commented on wb_mcu_fw_updater/update_monitor.py
>          downloaded_fw = fw_downloader.download_file(fw_downloader.urljoin(CONFIG['ROOT_URL'], released_fw_endpoint))
проглядел (+ еще такое было)
поправил

2022-01-18 12:09 UTC, vdromanov commented on wb-mcu-fw-updater
> +        update_monitor.RELEASE_INFO = releases.parse_releases(releases_fname)
сделал функцию, написал todo про класс

решение у меня - тоже такое себе
но предлагаю сейчас сильно не переделывать, а оставить на рефакторинг

2022-01-18 12:09 UTC, vdromanov commented on wb_mcu_fw_updater/update_monitor.py
> +        logging.warning('Device "%s" is not supported in release "%s %s"' % (fw_signature, str(release_info.get('SUITE')), str(release_info.get('RELEASE_NAME'))))
готово

2022-01-18 12:44 UTC, webconn commented on wb_mcu_fw_updater/releases.py
> +from posixpath import join as urljoin
Мне не нравится, что эта функция не совсем про url. Но раз уж она везде тут используется, то это требование скорее уходит в план по рефакторингу

2022-01-18 12:50 UTC, webconn commented on wb_mcu_fw_updater/update_monitor.py
> +        sys.modules[__name__].RELEASE_INFO = releases.parse_releases(releases_fname)  # instead of global
Это ещё зачем? `global` же можно было использовать

2022-01-18 13:54 UTC, webconn approved these changes

2022-01-20 20:44 UTC, vdromanov commented on wb_mcu_fw_updater/fw_downloader.py
> +                os.makedirs(file_saving_dir)  # py2 has not exist_ok param
это - обсуждаемая проблема, как оказалось
коммьюнити топит за такое решение

2022-01-20 20:49 UTC, vdromanov commented
благодаря тест-сьюту, вылезли еще интересности:
- если не установлен py2 - python-wb-mcu-fw-updater радостно собирается, но в нем пусто. Вернул старые build-depends (женкинс сейчас это никак не затрагивает, но так безопаснее)
- подставы с makedirs и JsonDecodeError

теперь точно всё работает

2022-01-21 09:39 UTC, webconn commented on wb_mcu_fw_updater/fw_downloader.py
> +                os.makedirs(file_saving_dir)  # py2 has not exist_ok param
Боль

2022-01-21 09:39 UTC, webconn approved these changes

2022-01-24 08:12 UTC, merged