Bugfix/serial port settings
wirenboard/wb-mcu-fw-updater pull request #24
Opened 2022-05-26 21:22 UTC by vdromanov

@wb-adegtyarev заметил, что упдатер 1.3.0 обновляет только по одному устройству в чемодане

причина - в чемодане у устройств BD 115200 (видимо, не проверил кейс, когда в сериале установлен нестандартный BD) => одно устройство прошивается, и порт остаётся c BD 9600 (после бутлоадера) => следующие устройства не могут перейти в бутлоадер

почему так получилось - в порции больших изменений инстансы Instrument'a (modbus_connection) стали ходить между функциями, а не создаваться каждый раз заново (а физически применение настроек порту дергается в ините Instrument'a) => всё работало по счастливому стечению обстоятельств

теперь применяем настройки к порту при каждом обращении к устройству

2022-05-27 09:04 UTC, webconn commented on wb_modbus/bindings.py
> +            tries = getattr(self, 'allowed_unsuccessful_tries', None) or ALLOWED_UNSUCCESSFUL_TRIES
Злая магия получилась, мне не нравится. Лучше из kwargs доставать, я считаю, а значение по умолчанию пусть через аргумент декоратора заходит. И назвать просто retries

2022-05-27 09:04 UTC, webconn commented on wb_modbus/bindings.py
> +                self.device.serial.close()
Тут получилось что-то плохо читаемое. Вроде проверяем, что не поставлен флаг `close_port_after_each_call`, и по нему тут закрываем порт?

2022-05-27 09:56 UTC, vdromanov commented on wb_modbus/bindings.py
> +                self.device.serial.close()
обсуждали в телеге; итог - подумать, нужна ли нам вся ветка "открывать-закрывать порт", или можно кидать эксепшон "зачем настраиваете закрытый порт"

2022-05-30 13:35 UTC, vdromanov commented on wb_modbus/bindings.py
> +            tries = getattr(self, 'allowed_unsuccessful_tries', None) or ALLOWED_UNSUCCESSFUL_TRIES
готово + добавил дебага

по мне - так меняем шило на мыло:
у нас много, где есть вот такое:
![2022-05-30_16-23-29](https://user-images.githubusercontent.com/25829054/171002380-db34bece-3db5-43a6-9889-57cc2b51ec46.png)
(декоратором обернута read_string)

=> можно: `device.read_u16(129, retries=10)` (удобно, согласен), но нельзя: `device.get_fw_signature(retries=10)`

а в варианте с self (исходном) можно подменять retries на лету (точно)
с другой стороны, занимаемся инжинирингом без реальной на то необходимости => предлагаю оставить переделанное и забить

2022-05-31 12:38 UTC, webconn commented on wb_modbus/bindings.py
> +            tries = getattr(self, 'allowed_unsuccessful_tries', None) or ALLOWED_UNSUCCESSFUL_TRIES
Мне на самом деле тут не понравилось, что мы декоратор можем применить только к методам определённых классов, и никак снаружи не можем узнать, каких. Протоколы завезли в слишком новый питон, они могли бы попытаться тут внести ясность, но при этом название декоратора всё равно никак не указывает, что я не мог бы применить его куда захочу

2022-05-31 12:45 UTC, webconn requested changes

2022-06-02 13:29 UTC, vdromanov commented on wb_modbus/bindings.py
> +            self._set_port_settings_raw(self.settings)
готово

в целом, можно wb_modbus подпричесать (есть несколько мест, где подоптимизировать можно) и выпустить в мир
мб историю заведем?

2022-06-03 11:25 UTC, webconn reviewed
Последнее чиним и вливаем :)

2022-06-03 11:25 UTC, webconn commented on wb_modbus/bindings.py
> +        def wrapper(self, *args, **kwargs):
тут не нужен self )

2022-06-03 14:48 UTC, vdromanov commented on wb_modbus/bindings.py
> +        def wrapper(self, *args, **kwargs):
проглядел

готово

2022-06-07 09:30 UTC, webconn approved these changes

2022-06-07 18:46 UTC, merged