Feature/49836 cli improvements
wirenboard/wb-mcu-fw-updater pull request #26
Opened 2022-07-11 07:24 UTC by vdromanov

- update-fw сам смотрит, в бутлоадере девайс или нет. Оживляет в любом случае. Если в бутлоадере и fw-sig достать не можем - предлагаем "recover"
- flash-file теперь не надо указывать -j (перезагрузку в бутлоадер) - разбирается сам
- --force убирает любую интерактивность
- --update-bl теперь ест branch и version

Несделанные хотелки:

- печатать версию упдатера при запуске. Версия встраивается ручками и довольно костыльно (а хочется - чтобы подтягивалась из дебианизации) => думаю, пока не надо
- показывать версии прошивок всех устройств в конфиге serial. Надо довольно глубоко копать; связанно с фичей по проверке обновлений; предлагаю сделать в её рамках

2022-07-11 19:16 UTC, webconn commented on wb-mcu-fw-updater
> +            logger.error("Check (%s) physical connection, slaveid and serial port!", device_str)
Сообщение в скобках тут в странном месте появилось, и содержание у него странное.

Во первых, надо ли писать постоянно про таймаут. Не написать ли в начале в `debug` или `info` "установлен таймаут такой-то для устройства такого-то".

Во-вторых, тут бы что-то в духе `Check physical connection of device %d on port %s`, или хотя бы `%s %d: can't connect, check physical connection or address`

2022-07-11 19:35 UTC, webconn commented on wb-mcu-fw-updater
> +                logger.info("Will flash latest released FW to bring %s (%s) alive", fw_sig, device_str)
Ну и ещё, везде имя устройства пишеся в скобках, и скобки в форматной строке, а не в имени, что добавляет ненужных повторов

2022-07-13 08:57 UTC, vdromanov commented on wb-mcu-fw-updater
> +                logger.info("Will flash latest released FW to bring %s (%s) alive", fw_sig, device_str)
готово

2022-07-13 08:57 UTC, vdromanov commented on wb-mcu-fw-updater
> +                                description='Wiren Board modbus devices firmware/bootloader update tool.', add_help=True)
да вроде бы нет
![2022-07-13_10-09-57](https://user-images.githubusercontent.com/25829054/178672789-2f063a2d-36f6-4299-bbde-6a3bfc181bc3.png)


единственное что - я пока ручками форматирую, чтобы +- одинаково оставалось

2022-07-13 08:57 UTC, vdromanov commented on wb-mcu-fw-updater
> +            logger.warning("Device (%s) supposed to be alive, but found in bootloader", device_str)
ну тут и правда, ай-ай: работало себе устройство спокойно, и вдруг оказалось в бутлоадере

сделал info

2022-07-13 08:57 UTC, vdromanov commented on wb-mcu-fw-updater
> +            logger.error("Check (%s) physical connection, slaveid and serial port!", device_str)
думаю, в ошибках про таймаут писать точно надо, т.к. на нем завязана логика вроде поиска настроек uart; определения, в бутлоадере девайс или нет => недостаточный таймаут (например, заданный из -T) может стать причиной ошибки

да и выглядит нестрашно вроде

вроде поменял сообщение (но по-моему, шило на мыло)

2022-07-14 19:33 UTC, vdromanov commented
завёз возможность восстановления девайса (в update-fw и update-bl) прошивкой по branch/version, ибо раньше было нелогично (можно было только релизной wbfw)

пришлось немного подвигать потроха

2022-07-22 10:31 UTC, vdromanov commented
по мотивам Жени в dev-чатике:
было
![2022-07-22_13-30-56](https://user-images.githubusercontent.com/25829054/180420960-36e33040-6dcb-4054-aca8-d35219479baf.png)

стало
![2022-07-22_13-29-18](https://user-images.githubusercontent.com/25829054/180420989-0f21984a-198d-4814-97f1-6150dff45daf.png)

2022-07-22 16:08 UTC, webconn commented on wb-mcu-fw-updater
> +                                description='Wiren Board modbus devices firmware/bootloader update tool.', add_help=True)
Black - твой друг, но не в этом PR. Можешь потом прогнать через него

2022-07-22 17:06 UTC, webconn requested changes
Код тяжеловато смотреть, конечно.

Я установил, попробовал прервать процесс обновления в середине (Ctrl-C) и получил вот такое:

```console
root@wirenboard-ATHFDT4L:~# wb-mcu-fw-updater update-all
2022-07-22 17:04:01,169 Will probe all devices on enabled serial ports of /etc/wb-mqtt-serial.conf:
2022-07-22 17:04:01,174 Probing WB-MSW v.3 (port: /dev/ttyRS485-1, slaveid: 188, uart_params: 115200N2, response_timeout: 0.50)...
2022-07-22 17:04:01,306 Probing Unknown (port: /dev/ttyRS485-1, slaveid: 16, uart_params: 115200N2, response_timeout: 0.50)...
2022-07-22 17:04:10,133 Update: 4.16.19 -> 4.18.10 (WB-MSW v.3 (188, /dev/ttyRS485-1))
2022-07-22 17:04:10,134 Flashing firmware to WB-MSW v.3 (188, /dev/ttyRS485-1)
2022-07-22 17:04:14,200 Flashing /var/lib/wb-mcu-fw-updater/msw3-49__4.18.10_master_98e5911.wbfw
 24%|###################################################2                                                                                                                                                               |50/206 24%|###################################################2                                                                                                                                                               |50/206
root@wirenboard-ATHFDT4L:~# wb-mcu-fw-updater update-all
2022-07-22 17:04:30,017 Will probe all devices on enabled serial ports of /etc/wb-mqtt-serial.conf:
2022-07-22 17:04:30,020 Probing WB-MSW v.3 (port: /dev/ttyRS485-1, slaveid: 188, uart_params: 115200N2, response_timeout: 0.50)...
2022-07-22 17:04:37,585 Probing Unknown (port: /dev/ttyRS485-1, slaveid: 16, uart_params: 115200N2, response_timeout: 0.50)...
2022-07-22 17:04:45,149 No answer from:
2022-07-22 17:04:45,150         Unknown (16, /dev/ttyRS485-1)
2022-07-22 17:04:45,151 Devices are possibly disconnected
2022-07-22 17:04:45,152 Now in bootloader:
2022-07-22 17:04:45,152         WB-MSW v.3 (188, /dev/ttyRS485-1)
2022-07-22 17:04:45,153 Try wb-mcu-fw-updater recover-all
2022-07-22 17:04:45,154 0 upgraded, 0 skipped upgrade, 1 stuck in bootloader, 1 disconnected and 0 too old for any updates.
```

2022-07-25 10:29 UTC, vdromanov commented on wb-mcu-fw-updater
> +    parser.add_argument('--force', action='store_true', dest='force', default=False,
готово

2022-07-25 10:29 UTC, vdromanov commented on wb_mcu_fw_updater/update_monitor.py
> +    if version == "latest" and retrieve_latest_vnum:  # TODO: put unstable_bl version to latest.txt on ci; then remove
https://wirenboard.bitrix24.ru/workgroups/group/218/tasks/task/view/51352/
в комменте - номер таски

2022-07-25 10:29 UTC, vdromanov commented on wb_mcu_fw_updater/update_monitor.py
> +        logger.debug("%s version has specified manually: %s", mode_name, version)
или я чего-то не понял, или здесь не так:
если есть branch и версия == release - делаем версию latest (в ифе про branch же)


+ эта логика давно работает; я только в функцию вытащил

2022-07-25 10:29 UTC, vdromanov commented on wb_mcu_fw_updater/update_monitor.py
> +        version=="release"; branch==<specified_branch> -> looking into branch/latest
надо

"release" - это значение по умолчанию для версии всего
дописал в коммент про это

2022-07-25 10:29 UTC, vdromanov commented on wb_mcu_fw_updater/update_monitor.py
> +                retrieve_latest_vnum=False)  # TODO: fix latest.txt for bl branches on ci
https://wirenboard.bitrix24.ru/workgroups/group/218/tasks/task/view/51352/
в комменте - номер таски

2022-07-25 10:31 UTC, vdromanov commented
завёз и для update-all (кажется, изначально только для update-fw обсуждалось.............)
![2022-07-25_13-26-56](https://user-images.githubusercontent.com/25829054/180756820-62c187ba-b205-4f6f-94dd-115549aed584.png)

2022-07-25 10:35 UTC, webconn commented on wb_mcu_fw_updater/update_monitor.py
> +        logger.debug("%s version has specified manually: %s", mode_name, version)
А зачем нужна вообще эта логика? В моём представлении человеку может захотеться установить прошивку такими способами:

1) из текущего релиза - самый простой вариант и должен быть по умолчанию;
2) специфической версии из main (или последний из main) - не должен быть случайно спутан с релизом
3) специфической версии из какой-то ещё ветки (или последний из ветки) - вообще особенно редкий случай, когда человеку надо потестить специфический для него фикс. Должен вызываться максимально явно, давая понять, что тут делается действие условно легитимное

Зачем смешивать здесь вместе релизы и ветки - я не понимаю. Релиз - это вообще отдельный специальный кейс, там ни версию, ни ветку указывать не надо

2022-07-25 10:49 UTC, vdromanov commented on wb_mcu_fw_updater/update_monitor.py
> +        logger.debug("%s version has specified manually: %s", mode_name, version)
ну чтобы снаружи было:
хочу из ветки (не такой и редкий случай, кстати; эмбеддеры что-то на форум выкладывают вроде) - `update-fw --branch <ветка>`, а не `update-fw --branch <ветка> --version latest`

можно такое сделать на уровне парсера, но там что-то прям сильно сложнее получается

2022-07-25 12:06 UTC, webconn approved these changes
В целом ок, можно поправить changelog и влить.

Я там по дороге ещё сделал задачку про пугающие логи в ситуации, когда устройство не обновилось по причине самой свежей прошивки, но это можно и потом решить

2022-07-26 14:43 UTC, merged