Feature/minimalmodbus public api
wirenboard/wb-mcu-fw-updater pull request #36
Opened 2022-11-24 19:02 UTC by vdromanov

как договаривались в телеге, завернул private-api минималмодбаса в public

нужно для device-manager'a (и в упдатере поправил то, что в магию минималмодбаса ходит)

2022-11-25 06:37 UTC, webconn requested changes

2022-11-25 06:37 UTC, webconn commented on wb_modbus/minimalmodbus.py
> +    )
```suggestion
def create_payload(*args, **kwargs):
    return _create_payload(*args, **kwargs)
```

И аналогично для остальных

2022-11-29 08:08 UTC, vdromanov commented
подумали-обсудили-решили отказываться от нашего minimalmodbus

=> решили, что в проектах пока остаются приватные методы => этот pr неактуален

2022-11-29 08:08 UTC, closed without merging

2022-11-29 08:49 UTC, webconn commented
> => решили, что в проектах пока остаются приватные методы => этот pr неактуален

Уточню - они там остаются до того момента, пока их не заменят методы из какого-нибудь uModbus. Хотим в итоге получить решение, в котором разбор сообщений и ввод-вывод лежат рядом друг с другом по отдельности, а не вложены (как в minimalmodbus, где надо передать библиотеке инструмент с реализацией ввода-вывода).

Проблема вложенных штук в том, что придётся всё API переписывать для добавления корутин и асинхронности. А при отдельных библиотеках для парсинга и IO можно делать для работы легковесные фасады такие, какие захотим, не вмешиваясь ни во что.