update_monitor: fix Neva slaveid parsing in serial config
wirenboard/wb-mcu-fw-updater pull request #37
Opened 2022-12-15 12:37 UTC by vdromanov

у Невы довольно странный формат slaveid (её серийник; c 0000 вначале)
и int(slaveid, 0) это не нравится

2022-12-16 09:25 UTC, vdromanov commented
у @wb-adegtyarev на демо-чемодане починилось

2022-12-16 13:34 UTC, webconn requested changes

2022-12-16 13:34 UTC, webconn commented on wb_mcu_fw_updater/update_monitor.py
> +                        )
Если так важно проверить что-то через try/except, заворачивай только ту часть, которую проверяешь. И ворнингами не разбрасывайся почём зря

```suggestion
                try:
                    parsed_slaveid = int(slaveid, 0)
                except ValueError:
                    logger.info(
                        'Device ("%s" %s) on %s seems not to be a WB-one; skipping', device_name, slaveid, port_name
                        )
                devices_on_port.add((device_name, parsed_slaveid, device_response_timeout))
```

2022-12-19 11:52 UTC, vdromanov commented on wb_mcu_fw_updater/update_monitor.py
> +                        )
готово

2022-12-19 13:24 UTC, webconn approved these changes

2022-12-27 19:41 UTC, merged