Feature/auto update unstable bl
wirenboard/wb-mcu-fw-updater pull request #76
Opened 2024-06-11 12:38 UTC by vdromanov

как-то так иногда получается, что забагованный бутлоадер попадает на устройства и на fw-releases

=> поговорили с @nikitoz236 - сделали логику "если текущей версии бутлоадера нет на s3 (увидели лажу и удалили руками) - обновляем бутлоадер без разговоров"

на картинке - подхакал чтение версии бутлоадера
![image](https://github.com/wirenboard/wb-mcu-fw-updater/assets/25829054/cb9dd7b2-3efd-4f0a-9ecf-926d5253fa35)

2024-06-13 09:51 UTC, webconn commented
а не лучше было для начала на том же fw-releases писать про забагованность бутлодера (и ещё ссылку на errata прикладывать) и тут во время обновления выводить какое-нибудь большое ругательство вместо того, чтобы форсировать потенциально опасную операцию?

2024-06-20 08:35 UTC, vdromanov commented
обсудили с @nikitoz236 - говорит, пока достаточно такого решения, а чтобы сделать хорошо - надо думать; будет думать позже

2024-06-23 22:14 UTC, evgeny-boger requested changes
Как-то непрозрачно. Я против, пока не переубедите.

2024-07-01 12:22 UTC, nikitoz236 commented
https://wirenboard.com/wiki/Bootloader:_Errata#ERRBOOT003:_%D0%9F%D0%BE%D1%81%D0%BB%D0%B5_%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F_%D0%BF%D1%80%D0%BE%D1%88%D0%B8%D0%B2%D0%BA%D0%B8_%D1%83%D1%81%D1%82%D1%80%D0%BE%D0%B9%D1%81%D1%82%D0%B2%D0%BE_%D0%BC%D0%BE%D0%B6%D0%B5%D1%82_%D0%BE%D1%81%D1%82%D0%B0%D1%82%D1%8C%D1%81%D1%8F_%D0%B2_%D0%B7%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D1%87%D0%B8%D0%BA%D0%B5_%D0%B8_%D0%BD%D0%B5_%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA%D0%B0%D1%82%D1%8C_%D0%BF%D1%80%D0%BE%D1%88%D0%B8%D0%B2%D0%BA%D1%83

2024-07-01 12:26 UTC, nikitoz236 commented
> Как-то непрозрачно. Я против, пока не переубедите.

https://wirenboard.com/wiki/Bootloader:_Errata#ERRBOOT003:_%D0%9F%D0%BE%D1%81%D0%BB%D0%B5_%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F_%D0%BF%D1%80%D0%BE%D1%88%D0%B8%D0%B2%D0%BA%D0%B8_%D1%83%D1%81%D1%82%D1%80%D0%BE%D0%B9%D1%81%D1%82%D0%B2%D0%BE_%D0%BC%D0%BE%D0%B6%D0%B5%D1%82_%D0%BE%D1%81%D1%82%D0%B0%D1%82%D1%8C%D1%81%D1%8F_%D0%B2_%D0%B7%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D1%87%D0%B8%D0%BA%D0%B5_%D0%B8_%D0%BD%D0%B5_%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA%D0%B0%D1%82%D1%8C_%D0%BF%D1%80%D0%BE%D1%88%D0%B8%D0%B2%D0%BA%D1%83

вот туть есть ерата. в которо написано почему будет плохо, если пользователи будут делать не такак как в этом исправлении.

Я понимаю что можно сделать лучше, добавить функций. Сделать показывание сообщеений. но:

	во первых - это отдельные задачи которые нужно делать, напомню что в releases.yaml ВООБЩЕ нет ничего про Bootloader, и надо будет много думать над тем как это сделать.
	во вторых - чем быстрее новый упдатер предотвратит действия пользователей тем меньше у нас будет гарантийных возвратов.
	в третих - а какже аджайл ?

2024-07-03 15:50 UTC, webconn commented
> вот туть есть ерата. в которо написано почему будет плохо, если пользователи будут делать не так, как в этом исправлении.

я почитал еррату и не понял, как это связано с этим PR. могу предположить, что загрузчик 1.4.0 просто сейчас удалён с S3?

> во первых - это отдельные задачи которые нужно делать, напомню что в releases.yaml ВООБЩЕ нет ничего про Bootloader, и надо будет много думать над тем как это сделать.

на самом деле может и не очень много, там просто будет процедура, похожая на текущую для прошивок

> во вторых - чем быстрее новый упдатер предотвратит действия пользователей тем меньше у нас будет гарантийных возвратов.

ну или внезапных кирпичей/потерянных конфигов, если мы что-то забыли и у кого-то найдётся ещё удалённая версия бутлодера

> в третих - а какже аджайл ?

аджайл не означает, что надо всё костылями подпирать

2024-09-16 11:14 UTC, nikitoz236 approved these changes

2024-09-16 12:18 UTC, merged